language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.net#nephia"
    on_success: change
    on_failure: always

