package Nephia::Setup;
use strict;
use warnings;
use File::Spec;
use Path::Class;
use Cwd;

sub create {
    my ( $class ) = @_;

    my $approot = approot( $class );
    $approot->mkpath( 1, 0755 );
    map {
        $approot->subdir($_)->mkpath( 1, 0755 );
    } qw( lib etc view root root/static t );

    $approot->file('app.psgi')->spew(
        psgi_file( $class )
    );

    my @classpath = split(/::/, $class. '.pm');
    my $classfile = pop( @classpath );

    $approot->subdir('lib', @classpath)->mkpath( 1, 0755 ) if @classpath;
    push @classpath, $classfile;

    $approot->file('lib', @classpath)->spew(
        app_class_file( $class )
    );

    $approot->file('view', 'index.tx')->spew(
        index_template_file( $class )
    );

    $approot->file('root', 'static', 'style.css')->spew(
        css_file()
    );

    $approot->file('Makefile.PL')->spew(
        makefile( $class )
    );

    $approot->file('t','001_basic.t')->spew(
        basic_test_file( $class )
    );
}

sub approot {
    my ( $class ) = @_;
    $class =~ s/::/-/g;
    return dir( File::Spec->catfile( getcwd(), $class ) );
}

sub psgi_file {
    my $class = shift;
    return <<EOF;
use strict;
use warnings;
use FindBin;

use lib ("\$FindBin::Bin/lib", "\$FindBin::Bin/extlib/lib/perl5");
use $class;
$class->run();
EOF
}

sub app_class_file {
    my $class = shift;
    my $classname = $class; $classname =~ s/::/-/g;
    return <<EOF;
package $class;
use strict;
use warnings;
use Nephia;

our \$VERSION = 0.01;

path '/' => sub {
    my \$req = shift;
    return {
        template => 'index.tx',
        title => '$class',
    };
};

1;
__END__

=head1 NAME

$classname - Web Application

=head1 SYNOPSIS

  \$ plackup

=head1 DESCRIPTION

$class is web application based Nephia.

=head1 AUTHOR

clever guy

=head1 SEE ALSO

Nephia

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
EOF
}

sub index_template_file {
    return <<EOF;
<html>
<head>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
  <link rel="stylesheet" href="/static/style.css" />
  <link rel="shortcut icon" href="/static/favicon.ico" />
  <title><: \$title :> - powerd by Nephia</title>
</head>
<body>
  <div class="title">
    <h1><: \$title :></h1>
  </div>
  <address class="generated-by">Generated by Nephia</address>
</body>
</html>
EOF
}

sub css_file {
    return <<EOF;
body {
    background: #45484d; /* Old browsers */
    background: -moz-linear-gradient(top,  #45484d 0%, #000000 100%); /* FF3.6+ */
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#45484d), color-stop(100%,#000000)); /* Chrome,Safari4+ */
    background: -webkit-linear-gradient(top,  #45484d 0%,#000000 100%); /* Chrome10+,Safari5.1+ */
    background: -o-linear-gradient(top,  #45484d 0%,#000000 100%); /* Opera 11.10+ */
    background: -ms-linear-gradient(top,  #45484d 0%,#000000 100%); /* IE10+ */
    background: linear-gradient(to bottom,  #45484d 0%,#000000 100%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#45484d', endColorstr='#000000',GradientType=0 ); /* IE6-9 */
    color: #eed;
    text-shadow: 3px 3px 3px #000;
}

div.title {
    width: 80%;
    margin: auto;
    margin-top: 20px;
    background: #ff5db1; /* Old browsers */
    background: -moz-linear-gradient(top,  #ff5db1 0%, #ef017c 100%); /* FF3.6+ */
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ff5db1), color-stop(100%,#ef017c)); /* Chrome,Safari4+ */
    background: -webkit-linear-gradient(top,  #ff5db1 0%,#ef017c 100%); /* Chrome10+,Safari5.1+ */
    background: -o-linear-gradient(top,  #ff5db1 0%,#ef017c 100%); /* Opera 11.10+ */
    background: -ms-linear-gradient(top,  #ff5db1 0%,#ef017c 100%); /* IE10+ */
    background: linear-gradient(to bottom,  #ff5db1 0%,#ef017c 100%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ff5db1', endColorstr='#ef017c',GradientType=0 ); /* IE6-9 */
    padding: 10px 30px;
    border-radius: 20px;
    box-shadow: 7px 10px 30px #000;
    color: #eed;
    text-shadow: 3px 3px 3px #000;
}

address.generated-by {
    width: 80%;
    padding: 0px 30px;
    margin: auto;
    margin-top: 20px;
    text-align: right;
    font-style: normal;
}

EOF
}

sub makefile {
    my $class = shift;
    my $classpath = File::Spec->catfile( 'lib', split(/::/, $class. '.pm') );
    return <<EOF;
use inc::Module::Install;
all_from '$classpath';

requires 'Nephia' => 0.01;

tests 't/*.t';

test_requires 'Test::More';

WriteAll;
EOF
}

sub basic_test_file {
    my $class = shift;
    return <<EOF;
use strict;
use warnings;
use Test::More;
BEGIN {
    use_ok( '$class' );
}
done_testing;
EOF
}

1;
